# this secret file is used to store the uname password for the mongo db

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo
type: Opaque
data:
  # the values in secret are base64 encoded, so we encode and keep them here
  mongo-username: cmFnaHU=
  mongo-password: cmFtamVl